# -*- coding: utf-8 -*-
"""Untitled14.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YBtHXn3-NlSp7LJiaIjdwuh3SMmKgVfT
"""

import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/archive (4).zip")

df.head()

df.info()

print(f"Number of duplicate rows: {df.duplicated().sum()}")

df.drop_duplicates(inplace=True)
print(f"Number of rows after removing duplicates: {df.shape[0]}")

df.isnull().sum()

sales_by_category = df.groupby('Category')['Sales'].sum().sort_values(ascending=False)
display(sales_by_category)

plt.figure(figsize=(10, 6))
sales_by_category.plot(kind='bar')
plt.title('Total Sales per Category')
plt.xlabel('Category')
plt.ylabel('Total Sales')
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

profit_by_category = df.groupby('Category')['Profit'].sum().sort_values(ascending=False)
display(profit_by_category)

plt.figure(figsize=(10, 6))
profit_by_category.plot(kind='bar')
plt.title('Total Profit per Category')
plt.xlabel('Category')
plt.ylabel('Total Profit')
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

sales_by_sub_category = df.groupby('Sub-Category')['Sales'].sum().sort_values(ascending=False)
display(sales_by_sub_category)

plt.figure(figsize=(12, 7))
sales_by_sub_category.plot(kind='bar')
plt.title('Total Sales per Sub-Category')
plt.xlabel('Sub-Category')
plt.ylabel('Total Sales')
plt.xticks(rotation=90)
plt.tight_layout()
plt.show()

